/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CA_Level = { 'final' : null } |
  { 'intermediate' : null } |
  { 'foundation' : null };
export interface ChapterProgress {
  'subject' : string,
  'completed' : boolean,
  'chapterId' : string,
  'caLevel' : CA_Level,
}
export type ExternalBlob = Uint8Array;
export interface PDFMetadata {
  'subject' : string,
  'blobKey' : ExternalBlob,
  'name' : string,
  'pdfId' : string,
  'caLevel' : CA_Level,
}
export interface StudySession {
  'durationMins' : bigint,
  'subject' : string,
  'timestamp' : Time,
  'sessionId' : string,
  'caLevel' : CA_Level,
}
export type Time = bigint;
export interface TimerSession {
  'durationMins' : bigint,
  'subject' : string,
  'timerId' : string,
  'caLevel' : CA_Level,
  'timerType' : { 'stopwatch' : null } |
    { 'pomodoro' : null },
}
export interface TimetableSlot {
  'subject' : string,
  'dayOfWeek' : string,
  'time' : string,
  'slotId' : string,
  'caLevel' : CA_Level,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdatePDFMetadata' : ActorMethod<[PDFMetadata], undefined>,
  'addOrUpdateTimetableSlot' : ActorMethod<[TimetableSlot], undefined>,
  'addTimerSession' : ActorMethod<[TimerSession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapterProgress' : ActorMethod<[], Array<ChapterProgress>>,
  'getPDFMetadata' : ActorMethod<[], Array<PDFMetadata>>,
  'getStudySessions' : ActorMethod<[], Array<StudySession>>,
  'getTimerSessions' : ActorMethod<[], Array<TimerSession>>,
  'getTimetable' : ActorMethod<[], Array<TimetableSlot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logStudySession' : ActorMethod<[StudySession], undefined>,
  'removePDFMetadata' : ActorMethod<[string], undefined>,
  'removeTimetableSlot' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChapterProgress' : ActorMethod<[ChapterProgress], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];