/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CA_Level = IDL.Variant({
  'final' : IDL.Null,
  'intermediate' : IDL.Null,
  'foundation' : IDL.Null,
});
export const PDFMetadata = IDL.Record({
  'subject' : IDL.Text,
  'blobKey' : ExternalBlob,
  'name' : IDL.Text,
  'pdfId' : IDL.Text,
  'caLevel' : CA_Level,
});
export const TimetableSlot = IDL.Record({
  'subject' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'time' : IDL.Text,
  'slotId' : IDL.Text,
  'caLevel' : CA_Level,
});
export const TimerSession = IDL.Record({
  'durationMins' : IDL.Nat,
  'subject' : IDL.Text,
  'timerId' : IDL.Text,
  'caLevel' : CA_Level,
  'timerType' : IDL.Variant({ 'stopwatch' : IDL.Null, 'pomodoro' : IDL.Null }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChapterProgress = IDL.Record({
  'subject' : IDL.Text,
  'completed' : IDL.Bool,
  'chapterId' : IDL.Text,
  'caLevel' : CA_Level,
});
export const Time = IDL.Int;
export const StudySession = IDL.Record({
  'durationMins' : IDL.Nat,
  'subject' : IDL.Text,
  'timestamp' : Time,
  'sessionId' : IDL.Text,
  'caLevel' : CA_Level,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdatePDFMetadata' : IDL.Func([PDFMetadata], [], []),
  'addOrUpdateTimetableSlot' : IDL.Func([TimetableSlot], [], []),
  'addTimerSession' : IDL.Func([TimerSession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapterProgress' : IDL.Func([], [IDL.Vec(ChapterProgress)], ['query']),
  'getPDFMetadata' : IDL.Func([], [IDL.Vec(PDFMetadata)], ['query']),
  'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getTimerSessions' : IDL.Func([], [IDL.Vec(TimerSession)], ['query']),
  'getTimetable' : IDL.Func([], [IDL.Vec(TimetableSlot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logStudySession' : IDL.Func([StudySession], [], []),
  'removePDFMetadata' : IDL.Func([IDL.Text], [], []),
  'removeTimetableSlot' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChapterProgress' : IDL.Func([ChapterProgress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CA_Level = IDL.Variant({
    'final' : IDL.Null,
    'intermediate' : IDL.Null,
    'foundation' : IDL.Null,
  });
  const PDFMetadata = IDL.Record({
    'subject' : IDL.Text,
    'blobKey' : ExternalBlob,
    'name' : IDL.Text,
    'pdfId' : IDL.Text,
    'caLevel' : CA_Level,
  });
  const TimetableSlot = IDL.Record({
    'subject' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'time' : IDL.Text,
    'slotId' : IDL.Text,
    'caLevel' : CA_Level,
  });
  const TimerSession = IDL.Record({
    'durationMins' : IDL.Nat,
    'subject' : IDL.Text,
    'timerId' : IDL.Text,
    'caLevel' : CA_Level,
    'timerType' : IDL.Variant({
      'stopwatch' : IDL.Null,
      'pomodoro' : IDL.Null,
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChapterProgress = IDL.Record({
    'subject' : IDL.Text,
    'completed' : IDL.Bool,
    'chapterId' : IDL.Text,
    'caLevel' : CA_Level,
  });
  const Time = IDL.Int;
  const StudySession = IDL.Record({
    'durationMins' : IDL.Nat,
    'subject' : IDL.Text,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
    'caLevel' : CA_Level,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdatePDFMetadata' : IDL.Func([PDFMetadata], [], []),
    'addOrUpdateTimetableSlot' : IDL.Func([TimetableSlot], [], []),
    'addTimerSession' : IDL.Func([TimerSession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapterProgress' : IDL.Func([], [IDL.Vec(ChapterProgress)], ['query']),
    'getPDFMetadata' : IDL.Func([], [IDL.Vec(PDFMetadata)], ['query']),
    'getStudySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getTimerSessions' : IDL.Func([], [IDL.Vec(TimerSession)], ['query']),
    'getTimetable' : IDL.Func([], [IDL.Vec(TimetableSlot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logStudySession' : IDL.Func([StudySession], [], []),
    'removePDFMetadata' : IDL.Func([IDL.Text], [], []),
    'removeTimetableSlot' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChapterProgress' : IDL.Func([ChapterProgress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };