/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimetableSlot {
    subject: string;
    dayOfWeek: string;
    time: string;
    slotId: string;
    caLevel: CA_Level;
}
export interface PDFMetadata {
    subject: string;
    blobKey: ExternalBlob;
    name: string;
    pdfId: string;
    caLevel: CA_Level;
}
export type Time = bigint;
export interface TimerSession {
    durationMins: bigint;
    subject: string;
    timerId: string;
    caLevel: CA_Level;
    timerType: Variant_stopwatch_pomodoro;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface StudySession {
    durationMins: bigint;
    subject: string;
    timestamp: Time;
    sessionId: string;
    caLevel: CA_Level;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ChapterProgress {
    subject: string;
    completed: boolean;
    chapterId: string;
    caLevel: CA_Level;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CA_Level {
    final_ = "final",
    intermediate = "intermediate",
    foundation = "foundation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_stopwatch_pomodoro {
    stopwatch = "stopwatch",
    pomodoro = "pomodoro"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdatePDFMetadata(meta: PDFMetadata): Promise<void>;
    addOrUpdateTimetableSlot(slot: TimetableSlot): Promise<void>;
    addTimerSession(session: TimerSession): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChapterProgress(): Promise<Array<ChapterProgress>>;
    getPDFMetadata(): Promise<Array<PDFMetadata>>;
    getStudySessions(): Promise<Array<StudySession>>;
    getTimerSessions(): Promise<Array<TimerSession>>;
    getTimetable(): Promise<Array<TimetableSlot>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logStudySession(session: StudySession): Promise<void>;
    removePDFMetadata(pdfId: string): Promise<void>;
    removeTimetableSlot(slotId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateChapterProgress(chapter: ChapterProgress): Promise<void>;
}
import type { CA_Level as _CA_Level, ChapterProgress as _ChapterProgress, ExternalBlob as _ExternalBlob, PDFMetadata as _PDFMetadata, StudySession as _StudySession, Time as _Time, TimerSession as _TimerSession, TimetableSlot as _TimetableSlot, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdatePDFMetadata(arg0: PDFMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdatePDFMetadata(await to_candid_PDFMetadata_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdatePDFMetadata(await to_candid_PDFMetadata_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateTimetableSlot(arg0: TimetableSlot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTimetableSlot(to_candid_TimetableSlot_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTimetableSlot(to_candid_TimetableSlot_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTimerSession(arg0: TimerSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimerSession(to_candid_TimerSession_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimerSession(to_candid_TimerSession_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapterProgress(): Promise<Array<ChapterProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapterProgress();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapterProgress();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPDFMetadata(): Promise<Array<PDFMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPDFMetadata();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPDFMetadata();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudySessions(): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySessions();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySessions();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimerSessions(): Promise<Array<TimerSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimerSessions();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimerSessions();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimetable(): Promise<Array<TimetableSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimetable();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimetable();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logStudySession(arg0: StudySession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logStudySession(to_candid_StudySession_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logStudySession(to_candid_StudySession_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removePDFMetadata(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePDFMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePDFMetadata(arg0);
            return result;
        }
    }
    async removeTimetableSlot(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTimetableSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTimetableSlot(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateChapterProgress(arg0: ChapterProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapterProgress(to_candid_ChapterProgress_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapterProgress(to_candid_ChapterProgress_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CA_Level_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CA_Level): CA_Level {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ChapterProgress_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChapterProgress): ChapterProgress {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PDFMetadata_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PDFMetadata): Promise<PDFMetadata> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_StudySession_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudySession): StudySession {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_TimerSession_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimerSession): TimerSession {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TimetableSlot_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimetableSlot): TimetableSlot {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    completed: boolean;
    chapterId: string;
    caLevel: _CA_Level;
}): {
    subject: string;
    completed: boolean;
    chapterId: string;
    caLevel: CA_Level;
} {
    return {
        subject: value.subject,
        completed: value.completed,
        chapterId: value.chapterId,
        caLevel: from_candid_CA_Level_n26(_uploadFile, _downloadFile, value.caLevel)
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    blobKey: _ExternalBlob;
    name: string;
    pdfId: string;
    caLevel: _CA_Level;
}): Promise<{
    subject: string;
    blobKey: ExternalBlob;
    name: string;
    pdfId: string;
    caLevel: CA_Level;
}> {
    return {
        subject: value.subject,
        blobKey: await from_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.blobKey),
        name: value.name,
        pdfId: value.pdfId,
        caLevel: from_candid_CA_Level_n26(_uploadFile, _downloadFile, value.caLevel)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    subject: string;
    timestamp: _Time;
    sessionId: string;
    caLevel: _CA_Level;
}): {
    durationMins: bigint;
    subject: string;
    timestamp: Time;
    sessionId: string;
    caLevel: CA_Level;
} {
    return {
        durationMins: value.durationMins,
        subject: value.subject,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        caLevel: from_candid_CA_Level_n26(_uploadFile, _downloadFile, value.caLevel)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    subject: string;
    timerId: string;
    caLevel: _CA_Level;
    timerType: {
        stopwatch: null;
    } | {
        pomodoro: null;
    };
}): {
    durationMins: bigint;
    subject: string;
    timerId: string;
    caLevel: CA_Level;
    timerType: Variant_stopwatch_pomodoro;
} {
    return {
        durationMins: value.durationMins,
        subject: value.subject,
        timerId: value.timerId,
        caLevel: from_candid_CA_Level_n26(_uploadFile, _downloadFile, value.caLevel),
        timerType: from_candid_variant_n38(_uploadFile, _downloadFile, value.timerType)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    dayOfWeek: string;
    time: string;
    slotId: string;
    caLevel: _CA_Level;
}): {
    subject: string;
    dayOfWeek: string;
    time: string;
    slotId: string;
    caLevel: CA_Level;
} {
    return {
        subject: value.subject,
        dayOfWeek: value.dayOfWeek,
        time: value.time,
        slotId: value.slotId,
        caLevel: from_candid_CA_Level_n26(_uploadFile, _downloadFile, value.caLevel)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    final: null;
} | {
    intermediate: null;
} | {
    foundation: null;
}): CA_Level {
    return "final" in value ? CA_Level.final : "intermediate" in value ? CA_Level.intermediate : "foundation" in value ? CA_Level.foundation : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stopwatch: null;
} | {
    pomodoro: null;
}): Variant_stopwatch_pomodoro {
    return "stopwatch" in value ? Variant_stopwatch_pomodoro.stopwatch : "pomodoro" in value ? Variant_stopwatch_pomodoro.pomodoro : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChapterProgress>): Array<ChapterProgress> {
    return value.map((x)=>from_candid_ChapterProgress_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PDFMetadata>): Promise<Array<PDFMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PDFMetadata_n29(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudySession>): Array<StudySession> {
    return value.map((x)=>from_candid_StudySession_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimerSession>): Array<TimerSession> {
    return value.map((x)=>from_candid_TimerSession_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimetableSlot>): Array<TimetableSlot> {
    return value.map((x)=>from_candid_TimetableSlot_n40(_uploadFile, _downloadFile, x));
}
function to_candid_CA_Level_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CA_Level): _CA_Level {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ChapterProgress_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterProgress): _ChapterProgress {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_PDFMetadata_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PDFMetadata): Promise<_PDFMetadata> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_StudySession_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudySession): _StudySession {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_TimerSession_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimerSession): _TimerSession {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_TimetableSlot_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimetableSlot): _TimetableSlot {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    dayOfWeek: string;
    time: string;
    slotId: string;
    caLevel: CA_Level;
}): {
    subject: string;
    dayOfWeek: string;
    time: string;
    slotId: string;
    caLevel: _CA_Level;
} {
    return {
        subject: value.subject,
        dayOfWeek: value.dayOfWeek,
        time: value.time,
        slotId: value.slotId,
        caLevel: to_candid_CA_Level_n11(_uploadFile, _downloadFile, value.caLevel)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    subject: string;
    timerId: string;
    caLevel: CA_Level;
    timerType: Variant_stopwatch_pomodoro;
}): {
    durationMins: bigint;
    subject: string;
    timerId: string;
    caLevel: _CA_Level;
    timerType: {
        stopwatch: null;
    } | {
        pomodoro: null;
    };
} {
    return {
        durationMins: value.durationMins,
        subject: value.subject,
        timerId: value.timerId,
        caLevel: to_candid_CA_Level_n11(_uploadFile, _downloadFile, value.caLevel),
        timerType: to_candid_variant_n17(_uploadFile, _downloadFile, value.timerType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationMins: bigint;
    subject: string;
    timestamp: Time;
    sessionId: string;
    caLevel: CA_Level;
}): {
    durationMins: bigint;
    subject: string;
    timestamp: _Time;
    sessionId: string;
    caLevel: _CA_Level;
} {
    return {
        durationMins: value.durationMins,
        subject: value.subject,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        caLevel: to_candid_CA_Level_n11(_uploadFile, _downloadFile, value.caLevel)
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    completed: boolean;
    chapterId: string;
    caLevel: CA_Level;
}): {
    subject: string;
    completed: boolean;
    chapterId: string;
    caLevel: _CA_Level;
} {
    return {
        subject: value.subject,
        completed: value.completed,
        chapterId: value.chapterId,
        caLevel: to_candid_CA_Level_n11(_uploadFile, _downloadFile, value.caLevel)
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: string;
    blobKey: ExternalBlob;
    name: string;
    pdfId: string;
    caLevel: CA_Level;
}): Promise<{
    subject: string;
    blobKey: _ExternalBlob;
    name: string;
    pdfId: string;
    caLevel: _CA_Level;
}> {
    return {
        subject: value.subject,
        blobKey: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.blobKey),
        name: value.name,
        pdfId: value.pdfId,
        caLevel: to_candid_CA_Level_n11(_uploadFile, _downloadFile, value.caLevel)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CA_Level): {
    final: null;
} | {
    intermediate: null;
} | {
    foundation: null;
} {
    return value == CA_Level.final ? {
        final_: null
    } : value == CA_Level.intermediate ? {
        intermediate: null
    } : value == CA_Level.foundation ? {
        foundation: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_stopwatch_pomodoro): {
    stopwatch: null;
} | {
    pomodoro: null;
} {
    return value == Variant_stopwatch_pomodoro.stopwatch ? {
        stopwatch: null
    } : value == Variant_stopwatch_pomodoro.pomodoro ? {
        pomodoro: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
